name: Sanitize

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  BUILD_TYPE: RelWithDebInfo
  EXTRA_FLAGS: -Wall -Wextra -fno-omit-frame-pointer -fsanitize=address

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure CMake
        run: |
          cmake -B ${{github.workspace}}/build     \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}   \
          -DCMAKE_CXX_FLAGS="${{env.EXTRA_FLAGS}}"
      - name: Build
        run: cmake --build ${{github.workspace}}/build
      - name: Show data
        run: ls -l data
      - name: Cleveland
        run: |
          ./build/src/signalserver \
          -dbg                     \
          -sdf data                \
          -lat 41.490298           \
          -lon -81.699936          \
          -txh 4                   \
          -f 900                   \
          -erp 20                  \
          -rxh 2                   \
          -rt -70 -dbm             \
          -m                       \
          -o cleveland             \
          -R 20                    \
          -pm 4
