name: C++

on:
  pull_request:
  push:
    branches: [main]
    tags: ["v*"]

env:
  BUILD_TYPE: RelWithDebInfo
  EXTRA_FLAGS: -Wall -Wextra -Werror -fno-omit-frame-pointer -fsanitize=address

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup | Configure
        run: |
          cmake -B ${{github.workspace}}/build     \
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}   \
          -DCMAKE_CXX_FLAGS="${{env.EXTRA_FLAGS}}"

      - name: Setup | Build
        run: cmake --build ${{github.workspace}}/build

      - name: Test | P2P
        run: |
          ./build/src/signalserver \
          -dbg                     \
          -sdf data                \
          -lat 41.491489           \
          -lon -81.695537          \
          -txh 10                  \
          -f 900                   \
          -erp 90                  \
          -rla 41.338866           \
          -rlo -81.597838          \
          -rxh 10                  \
          -rt -140 -dbm            \
          -m                       \
          -pm 4

      - name: Test | Image
        run: |
          ./build/src/signalserver \
          -dbg                     \
          -sdf data                \
          -t                       \
          -lat 41.491489           \
          -lon -81.695537          \
          -txh 10                  \
          -f 900                   \
          -erp 90                  \
          -rxh 10                  \
          -rt -140 -dbm            \
          -m                       \
          -R 20                    \
          -pm 4

      - name: Hygiene | Formatting
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '13'
          check-path: 'src'
